name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --all-extras
    
    - name: Lint with ruff
      run: uv run ruff check metrolinkTimes/
    
    - name: Check formatting with ruff
      run: uv run ruff format --check metrolinkTimes/
    
    - name: Test with pytest
      run: uv run pytest
    
    - name: Test import
      run: uv run python -c "from metrolinkTimes.api import app; print('Import successful')"

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -f Dockerfile -t metrolink-times:test .
    
    - name: Test Docker image
      run: |
        # Start container in background
        docker run -d --name test-container -p 5000:5000 metrolink-times:test
        sleep 10
        # Test if it's responding (will fail without config, but should start)
        docker logs test-container
        docker stop test-container